<p>
	<a href="<?php echo $this->url(
	    array(
	        'controller' => 'guestbook',
	        'action'     => 'sign'
	    ),
	    'default',
	    true) ?>">Sign Our Guestbook</a>
</p>
 
<h1>Guestbook Entries</h1>

<dl>
    <?php foreach ($this->entries as $entry): ?>

    <dt><?php echo $this->escape($entry->getUser()->getUsername()) ?> @ <?php echo date($entry->getCreated()); ?></dt>
    <dd><?php echo $this->escape($entry->getComment()) ?></dd>
    <?php endforeach ?>
</dl>
