<?php echo $this->filterForm ?>

<?php foreach ($this->videos as $video) : ?>
<div class="media">
    <a class="pull-left" href="#">
        <img class="media-object" src="http://i1.ytimg.com/vi/<?php echo $this->escape($video->youtube_key) ?>/default.jpg">
    </a>
    <div class="media-body">
        <h4 class="media-heading"><?php echo $this->escape($video->title) ?></h4>
    </div>
</div>
<?php endforeach ?>