<div class="media">
    <a class="pull-left" href="<?php echo $this->url(array('id' => $this->model->getId()), 'videos_view') ?>">
        <img class="media-object" src="http://i1.ytimg.com/vi/<?php echo $this->escape($this->model->getYoutubeKey()) ?>/default.jpg">
    </a>
    <div class="media-body">
        <a class="pull-left" href="<?php echo $this->url(array('id' => $this->model->getId()), 'videos_view') ?>">
            <h4 class="media-heading"><?php echo $this->escape($this->model->getTitle()) ?></h4>
        </a>
    </div>
</div>