<?php echo $this->doctype() ?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Zend Framework 1 Quickstart Application</title>
	<?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
	<div id="header" style="background-color: #EEEEEE; height: 30px;">
	    <div id="header-logo" style="float: left">
	        <b>ZF1 Quickstart Application</b>
	    </div>
	    <div id="header-navigation" style="float: right">
	        <a href="<?php echo $this->url(
	            array('controller'=>'guestbook'),
	            'default',
	            true) ?>">Guestbook</a>
	    </div>
	</div>
	 
	<?php echo $this->layout()->content ?>
	 
	</body>
</html>