<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <a class="brand" href="<?php echo $this->url(array('controller' => 'index'), 'default', true) ?>">ZF1 Quickstart Application</a>
                <ul class="nav">
                    <li><a href="<?php echo $this->url(
                            array('controller' => 'guestbook'),
                            'default',
                            true
                        ) ?>"><?php echo $this->translate('Guestbook'); ?></a></li>
                    <li><a href="<?php echo $this->url(
                            array('controller' => 'videos'),
                            'default',
                            true
                        ) ?>"><?php echo $this->translate('Videos'); ?></a></li>
                </ul>
                <ul class="nav pull-right">
                    <?php foreach ($this->loggedInAs() as $item) { ?>
                        <li><?php echo $item; ?></li>
                    <?php } ?>
                </ul>
            </div>
        </div>

        <?php if (count($this->messages)) : ?>
        <div class="container">
            <div class="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <ul id="messages">
                    <?php foreach ($this->messages as $message) : ?>
                        <li><?php echo $this->escape($this->translate($message)); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <?php endif; ?>

        <div class="container">
            <?php echo $this->layout()->content ?>
        </div>

        <div id="spinner">
            <img src="/img/spinner.gif" />
        </div>


        <?php echo $this->headScript() ?>
	</body>
</html>