<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <a class="brand" href="<?php echo $this->url(array('controller' => 'index'), 'default', true) ?>">ZF1 Quickstart Application</a>
                <ul class="nav">
                    <li><a href="<?php echo $this->url(
                            array('controller' => 'guestbook'),
                            'default',
                            true
                        ) ?>"><?php echo $this->translate('Guestbook'); ?></a></li>
                </ul>
                <ul class="nav pull-right">
                    <?php echo $this->loggedInAs(); ?>
                </ul>
            </div>
        </div>

        <div class="container">
            <?php echo $this->layout()->content ?>
        </div>

        <?php echo $this->headScript() ?>
	</body>
</html>